/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hbv.view;


import hbv.controller.*;
import hbv.model.*;


public class ReadReview extends javax.swing.JFrame {

    Object obj;
    private MainDisplay display;
    
    public ReadReview(Object obj, Review review, MainDisplay display) {
        initComponents();
        this.obj = obj;
        this.display = display;
        this.setTitle("Review");
        nameLab.setText(obj.toString());
        authorLab.setText(review.getWriter());
        reviewTitleLab.setText(review.getTitle());
        dateLab.setText(review.getDate());
        reviewTxt.setText(review.getText());
        this.setLocationRelativeTo(display);
        this.setResizable(false);
        this.setAlwaysOnTop(true);
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reviewTitleLab = new javax.swing.JLabel();
        authorStaticLab = new javax.swing.JLabel();
        dateStaticLab = new javax.swing.JLabel();
        nameLab = new javax.swing.JLabel();
        txtScroller = new javax.swing.JScrollPane();
        reviewTxt = new javax.swing.JTextArea();
        exitBtn = new javax.swing.JButton();
        authorLab = new javax.swing.JLabel();
        dateLab = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        reviewTitleLab.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        reviewTitleLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reviewTitleLab.setText("Review Title");

        authorStaticLab.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        authorStaticLab.setText("Author:");

        dateStaticLab.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        dateStaticLab.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        dateStaticLab.setText("Written:");

        nameLab.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        nameLab.setForeground(new java.awt.Color(51, 51, 255));
        nameLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLab.setText("Tour/Guide name");

        reviewTxt.setEditable(false);
        reviewTxt.setColumns(20);
        reviewTxt.setRows(5);
        txtScroller.setViewportView(reviewTxt);

        exitBtn.setText("Close");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        authorLab.setText("Name here");

        dateLab.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        dateLab.setText("date here");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtScroller)
                    .addComponent(reviewTitleLab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameLab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(authorStaticLab, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(authorLab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                        .addComponent(dateStaticLab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateLab, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(exitBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameLab, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(reviewTitleLab, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(authorStaticLab)
                    .addComponent(dateStaticLab)
                    .addComponent(authorLab)
                    .addComponent(dateLab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtScroller, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel authorLab;
    private javax.swing.JLabel authorStaticLab;
    private javax.swing.JLabel dateLab;
    private javax.swing.JLabel dateStaticLab;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel nameLab;
    private javax.swing.JLabel reviewTitleLab;
    private javax.swing.JTextArea reviewTxt;
    private javax.swing.JScrollPane txtScroller;
    // End of variables declaration//GEN-END:variables
}
