/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hbv.model;

import java.awt.Color;
import java.util.Date;

/**
 *
 * @author Hoai Nam Duc Tran
 */
public class ReviewCell extends javax.swing.JPanel {

    /**
     * Creates new form ReviewCell
     */
    public ReviewCell(String reviewTitle) {
        initComponents();
        this.listReviewTitle.setText(reviewTitle);
    }
    
    public void setLettersColor(Color color){
        listReviewTitle.setForeground(color);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listReviewTitle = new javax.swing.JLabel();

        listReviewTitle.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        listReviewTitle.setText("Title goes here");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listReviewTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(listReviewTitle)
                .addGap(0, 2, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel listReviewTitle;
    // End of variables declaration//GEN-END:variables
}
