/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hbv.model;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author Notandi
 */
public class TourCell extends javax.swing.JPanel {
 
    public TourCell(String tourName, ImageIcon rating, String date, String price) {
        initComponents();
        this.listName.setText(tourName);
        this.listRating.setText("");
        this.listRating.setIcon(rating);
        this.listDate.setText(date);
        this.listPrice.setText(price);
    }
    
    
    public void setLettersColor(Color color){
        listName.setForeground(color);
        listDate.setForeground(color);
        listPrice.setForeground(color);
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listName = new javax.swing.JLabel();
        listRating = new javax.swing.JLabel();
        listPrice = new javax.swing.JLabel();
        listDate = new javax.swing.JLabel();

        listName.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        listName.setText("Name goes here");

        listRating.setText("Image goes here");

        listPrice.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        listPrice.setText("Price goes here");

        listDate.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        listDate.setText("Date goes here");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listName, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(listPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listDate, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listRating))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listRating, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(listPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listDate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel listDate;
    private javax.swing.JLabel listName;
    private javax.swing.JLabel listPrice;
    private javax.swing.JLabel listRating;
    // End of variables declaration//GEN-END:variables
}
